# Numpy

In [4]:
import math
import os
import sys
import time

In [6]:
import numpy as np

plist = [1,2,3,4,5]
narr = np.array([1,2,3,4,5])

print(plist)
print(narr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
print(narr[2])
print(narr[0:3])
print(narr[4])

3
[1 2 3]
5


In [10]:
dir(narr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [12]:
m_dim2 = np.array([[1,2,3,4],
                  [2,4,6,8]])

m_dim2

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [14]:
m_dim2.ndim

2

In [16]:
narr.ndim

1

In [18]:
n_dim3 = np.array([[[1,2,3],[9,7,5]],
                  [[2,4,6],[7,6,5]],
                  [[0,0,0],[1,1,1]]])

n_dim3

array([[[1, 2, 3],
        [9, 7, 5]],

       [[2, 4, 6],
        [7, 6, 5]],

       [[0, 0, 0],
        [1, 1, 1]]])

In [20]:
n_dim3.ndim

3

In [22]:
m_dim2[0]

array([1, 2, 3, 4])

In [24]:
m_dim2[1]

array([2, 4, 6, 8])

In [26]:
m_dim2[1][2]

6

In [28]:
print(narr.shape)
print(m_dim2.shape)
print(n_dim3.shape)

(5,)
(2, 4)
(3, 2, 3)


In [30]:
n_dim3

array([[[1, 2, 3],
        [9, 7, 5]],

       [[2, 4, 6],
        [7, 6, 5]],

       [[0, 0, 0],
        [1, 1, 1]]])

In [32]:
narr.sum()

15

In [34]:
narr

array([1, 2, 3, 4, 5])

In [36]:
narr.min()

1

In [38]:
narr.max()

5

In [42]:
narr.std()

1.4142135623730951

In [44]:
narr.dtype

dtype('int32')

In [52]:
p1 = range(500,800,5)
n1 = np.arange(1000)

print(list(p1))
print(n1[150:160])

[500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775, 780, 785, 790, 795]
[150 151 152 153 154 155 156 157 158 159]


In [60]:
p1 = range(1000)
n1 = np.arange(1000)


print(sys.getsizeof(2))
print(sys.getsizeof(245))
print(sys.getsizeof('sdf'))
print(sys.getsizeof('d'))

print("Python List consume: ", sys.getsizeof(p1[2])*len(p1))
print("Numpy Array consume: ", n1.itemsize * n1.size)

28
28
44
42
Python List consume:  28000
Numpy Array consume:  4000


In [62]:


nt = n2 + n3
print(nt[0:10])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
nmt = n2 * n3
nmt[0:10]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [70]:
nst = n3 - n2
nst[0:15]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
new_arr = narr * 5
new_arr

array([ 5, 10, 15, 20, 25])

In [84]:
size = 10000000
p2 = range(size)
p3 = range(size)

n2 = np.arange(size)
n3 = np.arange(size)

start_time = time.time()
print(start_time)
p5 = []
for x,y in zip(p2, p3):
    p5.append(x+y)
print(time.time())
print("Python List took time:", (time.time() - start_time))

start_time = time.time()
p4 = [(x+y) for x,y in zip(p2, p3)]
print("Python List took time:", (time.time() - start_time))

start_time = time.time()
n5 = n2 + n3
print("Numpy Array took time:", (time.time() - start_time))
    

1726922513.6268294
1726922516.410715
Python List took time: 2.7838857173919678
Python List took time: 1.20078706741333
Numpy Array took time: 0.019060134887695312


In [82]:
print(p5[0:20])
print(n5[0:20])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [ ]:
dir(sys)

In [ ]:
dir(math)

In [ ]:
dir(os)

In [ ]:
dir(time)